AR			= ar
CC			= g++
JAVA		= javac

DEVCPP = d:/Dev-Cpp

TARGET_ARCH = linux

OPT    		= -fomit-frame-pointer -funroll-loops -march=i686 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -O2
DEBUG  		= -ggdb 
OTHER  		= -Wall  

INCLUDE		= -I. -I../include -Iinclude -I$(DEVCPP)/include -I$(DEVCPP)/include -I$(DEVCPP)/include/c++  -I$(DEVCPP)/include/c++/mingw32  -I$(DEVCPP)/include/c++/backward  -I$(DEVCPP)/include 
LIBRARY 	= -L. -L../lib -L$(DEVCPP)/lib -ljlogger

STD			= _GNU_SOURCE

CCFLAGS		= $(INCLUDE) $(DEBUG) $(OPT) $(OTHER) -D$(STD)

OBJS_teste = \
	   teste.o\

all: teste
	
teste: $(OBJS_teste)
	$(CC) $(CCFLAGS) $(OBJS_teste) -o teste $(LIBRARY)
        
.cpp.o: $<  
	$(CC) $(CCFLAGS) -c $< 

install:


clean:
	rm -rvf *.o *~ teste.exe 
