// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2012/1/6 ¤W¤È 10:22:28 from Type Library described below.

// ************************************************************************  //
// Type Lib: D:\WorkSpace\CMSCpp2.1\lib\EyeOneLib\EyeOne.dll (1)
// LIBID: {10A3A3EB-9E08-4B1A-8E14-7693FB50C5EC}
// LCID: 0
// Helpfile: D:\WorkSpace\CMSCpp2.1\lib\EyeOneLib\EyeOneCtrl.hlp
// HelpString: EyeOneCtrl ActiveX Control module
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINDOWS\system32\stdole2.tlb)
// ************************************************************************ //
#ifndef   EYEONECTRLLib_OCXH
#define   EYEONECTRLLib_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "EYEONECTRLLib_TLB.h"
namespace Eyeonectrllib_tlb
{

// *********************************************************************//
// HelpString: EyeOneCtrl ActiveX Control module
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TEyeOneCtrl
// Help String      : EyeOneCtrl Control
// Default Interface: _DEyeOneCtrl
// Def. Intf. Object: _DEyeOneCtrlDisp
// Def. Intf. DISP? : Yes
// Event   Interface: _DEyeOneCtrlEvents
// TypeFlags        : (34) CanCreate Control
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host EyeOneCtrl Control in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TEyeOneCtrl : public TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //

  // Default Interace of OCX
  //
  _DEyeOneCtrlDisp m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //

  // Static variables used by all instances of OCX proxy
  //
  static TControlData CControlData;
  static GUID         CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  _DEyeOneCtrlDisp __fastcall GetDefaultInterface();
  _DEyeOneCtrlDisp __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TEyeOneCtrl(TComponent* AOwner) : TOleControl(AOwner)
  {};
  virtual  __fastcall TEyeOneCtrl(HWND        Parent) : TOleControl(Parent)
  {};

  // OCX methods
  //
  BSTR            __fastcall GetDeviceInfo(BSTR axKey);
  long            __fastcall IsConnected(void);
  long            __fastcall KeyPressed(void);
  long            __fastcall Calibrate(void);
  long            __fastcall TriggerMeasurement(void);
  long            __fastcall SetOption(BSTR axKey, BSTR axValue);
  BSTR            __fastcall GetOption(BSTR axKey);
  long            __fastcall SetSubstrate(LPSAFEARRAY* xySubstrateSpectrum);
  long            __fastcall GetTriStimulus(LPSAFEARRAY* yxTriStimulus, long axIndex);
  long            __fastcall GetDensity(float* axDensity, long axIndex);
  long            __fastcall GetDensities(LPSAFEARRAY* yxDensities, long* pxAutoDensityIndex, 
                                          long axIndex);
  long            __fastcall GetSpectrum(LPSAFEARRAY* yxSpectrum, long axIndex);

  // OCX properties
  //
  __property _DEyeOneCtrlDisp ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property TabStop;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property Visible;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;

  // OCX properties
  //

  // OCX Events
  //
};
typedef TEyeOneCtrl  TEyeOneCtrlProxy;

};     // namespace Eyeonectrllib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Eyeonectrllib_tlb;
#endif

#pragma option pop

#endif // EYEONECTRLLib_OCXH
